version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    command: -p 5432
    ports:
      - "5432:5432"
    
  postgres2:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/pgsql/data2
    environment:
      POSTGRES_PASSWORD: postgrespassword
    command: -p 5431
    ports:
      - "5431:5431"

  graphql-engine:
    image: hasura/graphql-engine:v2.15.1
    depends_on:
    - "postgres"
    restart: always
    volumes:
      - ./noel/migrations:/hasura-migrations
      - ./noel/metadata:/hasura-metadata
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_SERVER_PORT: 8080
      HASURA_GRAPHQL_AUTH_HOOK: http://host.docker.internal:8000/auth/validate
      HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS: "true"
      API_URL: http://host.docker.internal:8000/
      HOTDOGS_URL: http://host.docker.internal:5001/v1/graphql
    ports:
      - "8080:8080"

  graphql-engine2:
    image: hasura/graphql-engine:v2.15.1
    depends_on:
    - "postgres2"
    restart: always
    volumes:
      - ./F&D/migrations:/hasura-migrations
      - ./F&D/metadata:/hasura-metadata
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres2:5431/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_SERVER_PORT: 5001
    ports:
      - "5001:5001"
volumes:
  db_data: